# Generated by Django 3.1.1 on 2021-02-17 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='content_message',
            field=models.TextField(default='hola'),
            preserve_default=False,
        ),
    ]
